name: Dev.to Post Workflow
on:
 schedule:
  - cron: '59 23 * * *'
 workflow_dispatch:

jobs:
 update-readme-with-blog:
  name: Update this repo's README with latest blog posts
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: gautamkrishnar/blog-post-workflow@master
     with:
      feed_list: 'https://dev.to/feed/bdfd2005'
      date_format: 'mmm d, yyyy'
      max_post_count: 3
      template: '<table style="border: 1px solid black">
       <tr>
       <td>
       <a href="$url" target="__blank">
       <h1 color="#333">$randomEmoji(ðŸ’¯,ðŸ”¥,ðŸ’«,ðŸš€,ðŸŒ®) $title</h1>
       </a>
       </td>$newline
       <td>
       <p color="#333">$description
       </p>
       </br>
       <small color="#888">Post Date:$date
       </small>
       </td>
       </tr>
       </table>'
